name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: leftrightleft/gha-lint-yaml@master
        with:
          path: "tests/valid.yml"
      # - name: Check outputs and modified files
      #   run: |
      #               test "${{ steps.selftest.outputs.warnings }}" == "1"